


COUNTRY_CHOICES = [
    ('AR', 'Argentina'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('BE', 'Belgium'),
    ('BR', 'Brazil'),
    ('CA', 'Canada'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('CR', 'Costa Rica'),
    ('HR', 'Croatia'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czech Republic'),
    ('DK', 'Denmark'),
    ('EG', 'Egypt'),
    ('EE', 'Estonia'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('DE', 'Germany'),
    ('GR', 'Greece'),
    ('HK', 'Hong Kong'),
    ('HU', 'Hungary'),
    ('IS', 'Iceland'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IE', 'Ireland'),
    ('IL', 'Israel'),
    ('IT', 'Italy'),
    ('JP', 'Japan'),
    ('KE', 'Kenya'),
    ('LV', 'Latvia'),
    ('LT', 'Lithuania'),
    ('MY', 'Malaysia'),
    ('MX', 'Mexico'),
    ('NL', 'Netherlands'),
    ('NZ', 'New Zealand'),
    ('NG', 'Nigeria'),
    ('NO', 'Norway'),
    ('PK', 'Pakistan'),
    ('PE', 'Peru'),
    ('PH', 'Philippines'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('RO', 'Romania'),
    ('RU', 'Russia'),
    ('SG', 'Singapore'),
    ('ZA', 'South Africa'),
    ('ES', 'Spain'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('TH', 'Thailand'),
    ('TR', 'Turkey'),
    ('UA', 'Ukraine'),
    ('AE', 'United Arab Emirates'),
    ('GB', 'United Kingdom'),
    ('US', 'United States'),
    ('OT', 'Other')
]
