# Generated by Django 5.0.6 on 2024-08-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='commentator',
            new_name='user',
        ),
    ]
