# Generated by Django 5.0.6 on 2024-08-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread_app', '0003_rename_commentator_commentmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
