# Generated by Django 5.0.6 on 2024-09-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread_app', '0004_threadmodel_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmodel',
            old_name='photo',
            new_name='image',
        ),
    ]
