# Generated by Django 5.0.6 on 2024-09-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread_app', '0005_rename_photo_threadmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmodel',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
