# Generated by Django 5.0.6 on 2024-08-05 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thread_app', '0003_rename_commentator_commentmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='thread_app.commentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment_link', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ThreadLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='thread_app.threadmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('thread_link', 'user')},
            },
        ),
    ]
