# Generated by Django 5.0.6 on 2024-08-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikemodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='threadlikemodel',
            name='updated_at',
        ),
    ]
