# Generated by Django 5.0.6 on 2024-08-08 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_app', '0002_remove_commentlikemodel_updated_at_and_more'),
        ('thread_app', '0003_rename_commentator_commentmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlikemodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='threadlikemodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='commentlikemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threadlikemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_thread_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commentlikemodel',
            unique_together={('user', 'comment_link')},
        ),
        migrations.AlterUniqueTogether(
            name='threadlikemodel',
            unique_together={('user', 'thread_link')},
        ),
        migrations.CreateModel(
            name='SavedThreadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_threads', to='thread_app.threadmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
